version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  mysql-dev:
    image: mysql:8.0
    container_name: mysql-dev-container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 170490
      MYSQL_DATABASE: gestaoresiduos_dev
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  mysql-prd:
    image: mysql:8.0
    container_name: mysql-prd-container
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 170490
      MYSQL_DATABASE: gestaoresiduos_prd
    volumes:
      - mysql_prd_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  gestaoderesiduos:
    build: .
    container_name: gestaoderesiduos-container
    ports:
      - "8080:8080"
    environment:
      - PROFILE=prd
    depends_on:
      mysql-dev:
        condition: service_healthy
    networks:
      - app_network
    restart: on-failure

volumes:
  mysql_dev_data:
  mysql_prd_data: