CREATE SEQUENCE SEQ_AGENDAMENTOS 
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_LIXEIRAS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

 CREATE TABLE IF NOT EXISTS "TBL_AGENDAMENTOS" 
    ("ID_AGENDAMENTO" NUMBER(19,0) NOT NULL ENABLE, 
    "DATA" DATE, 
    "ROTA" VARCHAR2(255 CHAR), 
    "VEICULO" VARCHAR2(255 CHAR), 
	PRIMARY KEY ("ID_AGENDAMENTO"));

  CREATE TABLE IF NOT EXISTS "TBL_LIXEIRAS" 
(
    "ID_LIXEIRA" NUMBER(19,0) NOT NULL ENABLE,
    "CAPACIDADE" FLOAT(53),
    "ENDERECO" VARCHAR2(255 CHAR),
    "LOTADA" NUMBER(1,0),
    "ID_AGENDAMENTO" NUMBER(19,0),
    PRIMARY KEY ("ID_LIXEIRA"),
    CONSTRAINT fk_agendamento FOREIGN KEY ("ID_AGENDAMENTO")
    REFERENCES "TBL_AGENDAMENTOS" ("ID_AGENDAMENTO") ENABLE
);
