CREATE TABLE IF NOT EXISTS TBL_AGENDAMENTOS (
    ID_AGENDAMENTO BIGINT NOT NULL AUTO_INCREMENT,
    DATA DATE,
    ROTA VARCHAR(255),
    VEICULO VARCHAR(255),
    PRIMARY KEY (ID_AGENDAMENTO)
);

CREATE TABLE IF NOT EXISTS TBL_LIXEIRAS (
    ID_LIXEIRA BIGINT NOT NULL AUTO_INCREMENT,
    CAPACIDADE DOUBLE,
    ENDERECO VARCHAR(255),
    LOTADA TINYINT(1),
    ID_AGENDAMENTO BIGINT,
    PRIMARY KEY (ID_LIXEIRA),
    CONSTRAINT fk_agendamento FOREIGN KEY (ID_AGENDAMENTO)
        REFERENCES TBL_AGENDAMENTOS(ID_AGENDAMENTO)
        ON DELETE SET NULL ON UPDATE CASCADE
);